<?php

namespace Cupon\BackendBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class TiendaController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Cupon\BackendBundle\Controller\TiendaController();
        return $instance;
    }
}
