<?php

namespace Cupon\TiendaBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ExtranetController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Cupon\TiendaBundle\Controller\ExtranetController();
        return $instance;
    }
}
