parameters:
#    contrato.example.class: Cupon\ContratoBundle\Example

services:
#    contrato.example:
#        class: %contrato.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
